/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#2b3437",
        "error-dim": "#4e0309",
        "surface-dim": "#d1dce0",
        "on-error-container": "#752121",
        "surface-container": "#eaeff1",
        "outline": "#737c7f",
        "primary": "#5f5e5e",
        "on-background": "#2b3437",
        "tertiary": "#5b5f65",
        "on-tertiary-container": "#575c61",
        "on-tertiary-fixed": "#454a4f",
        "background": "#f8f9fa",
        "on-surface-variant": "#586064",
        "tertiary-fixed-dim": "#e2e6ec",
        "on-primary-fixed-variant": "#5c5b5b",
        "secondary-dim": "#505358",
        "surface-container-low": "#f1f4f6",
        "on-secondary-container": "#4f5256",
        "inverse-surface": "#0c0f10",
        "surface-container-high": "#e2e9ec",
        "tertiary-fixed": "#f0f4fa",
        "surface-bright": "#f8f9fa",
        "secondary": "#5c5f64",
        "on-tertiary-fixed-variant": "#62676c",
        "primary-dim": "#535252",
        "on-primary-container": "#525151",
        "on-tertiary": "#f6f9ff",
        "error": "#9f403d",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#faf7f6",
        "on-primary-fixed": "#403f3f",
        "on-secondary": "#f7f9fe",
        "primary-container": "#e5e2e1",
        "secondary-fixed": "#e0e2e8",
        "secondary-fixed-dim": "#d2d4da",
        "surface-tint": "#5f5e5e",
        "primary-fixed": "#e5e2e1",
        "primary-fixed-dim": "#d6d4d3",
        "secondary-container": "#e0e2e8",
        "on-secondary-fixed-variant": "#585c60",
        "surface": "#f8f9fa",
        "inverse-primary": "#ffffff",
        "on-error": "#fff7f6",
        "outline-variant": "#abb3b7",
        "inverse-on-surface": "#9b9d9e",
        "tertiary-container": "#f0f4fa",
        "error-container": "#fe8983",
        "tertiary-dim": "#4f5459",
        "on-secondary-fixed": "#3c4044",
        "surface-variant": "#dbe4e7",
        "surface-container-highest": "#dbe4e7"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
